version: '3.8'

services:
  backend:
    volumes:
      - ./src:/app/src
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    # Usamos una imagen de node directamente en lugar de Nginx
    image: node:20-alpine
    # Evitamos que use el 'build' del archivo original
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_PROXY_TARGET=http://backend:8000
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
